services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: ${APP_ENV:-local}
    ports:
      - "3000:3000"
    restart: unless-stopped
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    environment:
      - NODE_ENV=${APP_ENV:-local}
    networks:
      - web
  
networks:
  web:
    driver: bridge